### ISSUE TITLE
Suggestion: Invasion rework akin to gym sub rework

### ISSUE THREAD

**Issue by nileplumb** [versx/WhMgr-UI#38]
allow ability to cross reference specific stop invasion alerts, alongside geofence restricted and/or settings max distance alerts.

eg:

- all invasions at My Cool Pokéstop
- dark, tier 2, dragon & sierra invasions in 'city west' Geofence
- dragon invasions within 2000m from my settings location

**Comment by versx** [comment]
Fixed in https://github.com/versx/WhMgr-UI/releases/tag/1.7.0-1
