### ISSUE TITLE
Bug with editing Minimum IV and IV-List

### ISSUE THREAD

**Issue by ZombieCorn80** [versx/WhMgr-UI#42]
a subscription for all pokemon with "Minimun IV" empty and IV-List 0/0/0 and 15/15/15 for all 0% and 100% in one area.

the subscription for a pokemon edited -> minimum IV 0 and IV list empty (area the same)

now I want to edit it back to Minimun IV empty and IV-List 0/0/0 and 15/15/15 for all 0% and 100% (area the same) but after saving, 100 is automatically entered in Minimum IV if I leave it blank

**Comment by versx** [comment]
Fixed in https://github.com/versx/WhMgr-UI/commit/3809e62a1680c4148210236fcb222a551e1e8a01
