### ISSUE TITLE
Unable to select areas on the map in Safari

### ISSUE THREAD

**Issue by corbindk** [versx/WhMgr-UI#48]
Firefox, Chrome, and Samsung internet tested and working.

Safari mobile and desktop not selecting

**Comment by versx** [comment]
~Tried clearing cache? City selection works for me via macOS Big Sur on M1. 🤔~
Nevermind I was testing on Chrome, also doesn't work for me on Safari.
Weird I was able to get it to select once but can't do it again lol.

**Comment by clburlison** [comment]
Safari is gonna Safari. 🙃  The select all and select none buttons for the map works however that isn't the most useful.

**Comment by clburlison** [comment]
> Tested with Leaflet 1.7.0 in Firefox, Chrome, and Safari (1.7.1 does not work; see FAQ below). Tested with Font Awesome 4.7.
> Source - https://github.com/domoritz/leaflet-locatecontrol

Looks like downgrading to 1.7.0 here might fix the problem. <https://github.com/versx/WhMgr-UI/blob/8ebc4e7ca1518b9698336eb25bacadee7b2ec96c/src/views/header.mustache#L28>

Testing on corbin's instance now.

**Comment by versx** [comment]
> > Tested with Leaflet 1.7.0 in Firefox, Chrome, and Safari (1.7.1 does not work; see FAQ below). Tested with Font Awesome 4.7.
> > Source - https://github.com/domoritz/leaflet-locatecontrol
> 
> Looks like downgrading to 1.7.0 here might fix the problem.
> 
> https://github.com/versx/WhMgr-UI/blob/8ebc4e7ca1518b9698336eb25bacadee7b2ec96c/src/views/header.mustache#L28
> 
> Testing on corbin's instance now.

Eagerly awaiting your reply. 👀 ❤️

**Comment by corbindk** [comment]
> Weird I was able to get it to select once but can't do it again lol.

Found how you did it, If you select a new location from the dropdown, the very first click/tap on the map will select an area. But then you have to change locations again from the dropdown to select another.
