### ISSUE TITLE
Empty city list saved with empty string

### ISSUE THREAD

**Issue by versx** [versx/WhMgr-UI#61]

**Comment by clburlison** [comment]
I'm not able to replicate this issue on the latest commits. Possibly addressed in https://github.com/versx/WhMgr-UI/commit/45ebe68d7b1c740be514ff87adbaa832e0b9b212#diff-f8779a12de525c26ac5b5a00c9c37fa6f80503220d3b772cd73769feeca97f50R8-R21 ?

**Comment by versx** [comment]
> I'm not able to replicate this issue on the latest commits. Possibly addressed in [45ebe68#diff-f8779a12de525c26ac5b5a00c9c37fa6f80503220d3b772cd73769feeca97f50R8-R21](https://github.com/versx/WhMgr-UI/commit/45ebe68d7b1c740be514ff87adbaa832e0b9b212#diff-f8779a12de525c26ac5b5a00c9c37fa6f80503220d3b772cd73769feeca97f50R8-R21) ?

IIRC this might have been related to a different commit that fixed it. Should be closed though, thank you.
