### ISSUE TITLE
Feature Request: Only One Role, configurable per Discord

### ISSUE THREAD

**Issue by SenorKarlos** [versx/WhMgr-UI#73]
This will need to be in WhMgr as well, so will make one over there as well. I'm using several discords and websites to organize zones and have my 'Primary Discord' with only setup & purchasing information, as well as statistics. One of those statistics is the users 'Primary Zone', now being collected via means of role assignment in the Primary Discord.

Being as people are annoying and can't read, I want to be able to set that Discord to only allow one role selection from the list, then in the Discords with multiple zone categories for the actual alerts, be able to select as many as they like as it is now.

**Comment by versx** [comment]
wut, you can set one role in the donor role ids list.

**Comment by SenorKarlos** [comment]
How do I word this better.... I don't want them to only have one option. I want them to have all 100+ zone roles on the main server available, but only be able to choose one (and have the all option disappear, come to think). If they choose another, the first one gets removed, and if they try and choose multiple it errors (or is just a scroll dropdown with a single selection). But it needs to be per server so that normal role selection can happen on the other Discords linked.

Know what I mean now?

**Comment by versx** [comment]
Isn't there a bot that does this already that Chuck made and I think Kasmar maintains?

**Comment by SenorKarlos** [comment]
For synch across multiple guilds, yes. Nothing that allows users to select a role like WhMgr. I am using both.

Stripe program gives main access roles
Main discord they choose ONE extra role to identify thier primary zone with WhMgr <== this request, let me restrict it
Chuck's snyc bot provides the access roles to other discords
Users then select as many Zone roles in the sub-discords as they want pre-set feeds for

**Comment by versx** [comment]
> For synch across multiple guilds, yes. Nothing that allows users to select a role like WhMgr. I am using both.
> 
> Stripe program gives main access roles Main discord they choose ONE extra role to identify thier primary zone with WhMgr <== this request, let me restrict it Chuck's snyc bot provides the access roles to other discords Users then select as many Zone roles in the sub-discords as they want pre-set feeds for

If I'm understanding
